<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-01T12:13:07 IST" name="Default suite" finished-at="2023-03-01T12:14:12 IST" duration-ms="65071">
    <groups>
    </groups>
    <test started-at="2023-03-01T12:13:07 IST" name="Default test" finished-at="2023-03-01T12:14:12 IST" duration-ms="65071">
      <class name="TestScripts.fourthtest">
        <test-method is-config="true" signature="classConfiguration()[pri:0, instance:TestScripts.fourthtest@c88a337]" started-at="2023-03-01T12:13:07 IST" name="classConfiguration" finished-at="2023-03-01T12:13:08 IST" duration-ms="975" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classConfiguration -->
        <test-method is-config="true" signature="methodConfiguration()[pri:0, instance:TestScripts.fourthtest@c88a337]" started-at="2023-03-01T12:13:08 IST" name="methodConfiguration" finished-at="2023-03-01T12:13:18 IST" duration-ms="10318" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodConfiguration -->
        <test-method signature="foruthtest()[pri:0, instance:TestScripts.fourthtest@c88a337]" started-at="2023-03-01T12:13:18 IST" name="foruthtest" finished-at="2023-03-01T12:14:11 IST" duration-ms="53345" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Skillrary] but found [[[ChromeDriver: chrome on WINDOWS (c7d0eaaeb616718b549fd0f256436e93)] -> xpath: //div[@class='navbar-header']]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Skillrary] but found [[[ChromeDriver: chrome on WINDOWS (c7d0eaaeb616718b549fd0f256436e93)] -> xpath: //div[@class='navbar-header']]]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestScripts.fourthtest.foruthtest(fourthtest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- foruthtest -->
        <test-method is-config="true" signature="methodTearDown()[pri:0, instance:TestScripts.fourthtest@c88a337]" started-at="2023-03-01T12:14:11 IST" name="methodTearDown" finished-at="2023-03-01T12:14:12 IST" duration-ms="379" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodTearDown -->
        <test-method is-config="true" signature="classTearDown()[pri:0, instance:TestScripts.fourthtest@c88a337]" started-at="2023-03-01T12:14:12 IST" name="classTearDown" finished-at="2023-03-01T12:14:12 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classTearDown -->
      </class> <!-- TestScripts.fourthtest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
